/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava.vue.graph;

import java.awt.Color;
import javax.swing.JOptionPane;
import projetjava.modele.Enseignant;
import projetjava.modele.Modele;

/**
 *
 * @author Fabrice
 */
public class AjoutEnseignant extends javax.swing.JPanel {
    private Modele m;

    /**
     * Creates new form AjoutEnseignant
     */
    public AjoutEnseignant() {
        initComponents();
    }
    
    public void setModele(Modele m){
       this.m = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lIdProf = new javax.swing.JLabel();
        tfIdProf = new javax.swing.JTextField();
        lNom = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        lPrenom = new javax.swing.JLabel();
        tfPrenom = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 500));
        setLayout(new java.awt.GridLayout(4, 2, 3, 3));

        lIdProf.setText("Id professeur : ");
        add(lIdProf);
        lIdProf.getAccessibleContext().setAccessibleName("lIdProf");

        tfIdProf.setToolTipText("");
        add(tfIdProf);
        tfIdProf.getAccessibleContext().setAccessibleName("tfIdProf");

        lNom.setText("Nom : ");
        add(lNom);
        lNom.getAccessibleContext().setAccessibleName("lNom ");

        add(tfNom);
        tfNom.getAccessibleContext().setAccessibleName("tfNom");

        lPrenom.setText("Prénom :");
        add(lPrenom);
        lPrenom.getAccessibleContext().setAccessibleName("lPrenom");

        add(tfPrenom);
        tfPrenom.getAccessibleContext().setAccessibleName("tfPrenom");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        add(btnOk);
        btnOk.getAccessibleContext().setAccessibleName("btnOk");

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        add(btnAnnuler);
        btnAnnuler.getAccessibleContext().setAccessibleName("btnAnnuler");
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        tfIdProf.setBackground(Color.white);
        tfNom.setBackground(Color.white);
        tfPrenom.setBackground(Color.white);
        boolean erreur=false;
        
        String idprof=tfIdProf.getText();
        if (idprof.trim().equals("")) {
            erreur =true;
            tfIdProf.setBackground(Color.red);
        }
        
        String nom=tfNom.getText();
        if (nom.trim().equals("")) {
            erreur =true;
            tfNom.setBackground(Color.red);
        }
        
        String prenom=tfPrenom.getText();
        if (prenom.trim().equals("")) {
            erreur =true;
            tfPrenom.setBackground(Color.red);
        }
        
       if(!erreur) {
           Enseignant e = new Enseignant(idprof, nom, prenom);
           String msg = m.ajoutEnseignant(e);
             JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);
       }  
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        tfIdProf.setText("");
        tfNom.setText("");
        tfPrenom.setText("");
        tfIdProf.setBackground(Color.white);
        tfNom.setBackground(Color.white);
        tfPrenom.setBackground(Color.white);
    }//GEN-LAST:event_btnAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lIdProf;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lPrenom;
    private javax.swing.JTextField tfIdProf;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    // End of variables declaration//GEN-END:variables
}



