/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava.vue.graph;

import java.awt.CardLayout;
import projetjava.modele.Modele;
/**
 *
 * @author Fabrice
 */
public class TestAjoutClasses extends javax.swing.JFrame {

    /**
     * Creates new form TestAjoutClasses
     */
    public TestAjoutClasses() {
        initComponents();
        Modele m = Modele.getInstance();
        c1.setModele(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c1 = new projetjava.vue.graph.AjoutClasses();
        ajoutEnseignant1 = new projetjava.vue.graph.AjoutEnseignant();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuClasses = new javax.swing.JMenu();
        AjoutClasses = new javax.swing.JMenuItem();
        menuEnseignants = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        c1.setName("c1"); // NOI18N
        getContentPane().add(c1, "c1");
        getContentPane().add(ajoutEnseignant1, "e1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        MenuClasses.setText("Classes");

        AjoutClasses.setText("Ajouter une classe");
        AjoutClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutClassesActionPerformed(evt);
            }
        });
        MenuClasses.add(AjoutClasses);

        jMenuBar1.add(MenuClasses);

        menuEnseignants.setText("Enseignants");

        jMenuItem2.setText("Ajouter un enseignant");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuEnseignants.add(jMenuItem2);

        jMenuBar1.add(menuEnseignants);
        menuEnseignants.getAccessibleContext().setAccessibleName("");

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutClassesActionPerformed
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(this.getContentPane(), "c1");
    }//GEN-LAST:event_AjoutClassesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(this.getContentPane(), "e1");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAjoutClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAjoutClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAjoutClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAjoutClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAjoutClasses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjoutClasses;
    private javax.swing.JMenu MenuClasses;
    private projetjava.vue.graph.AjoutEnseignant ajoutEnseignant1;
    private projetjava.vue.graph.AjoutClasses c1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuEnseignants;
    // End of variables declaration//GEN-END:variables
}
